spring.application.name=springboot

# Database Configuration (using GitHub secrets)
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
spring.datasource.username=${MYSQL_USER}  # Use MYSQL_USER alias
spring.datasource.password=${MYSQL_ROOT_PASSWORD}  # Ensure correct reference

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
spring.devtools.add-properties=false
